# frozen_string_literal: true

# This file was generated by https://github.com/petrgazarov/git-repo-name/blob/main/.github/workflows/release_packages.yml
class GitRepoName < Formula
  desc '"git-repo-name" – CLI to sync repository name between local and remote'
  homepage "https://github.com/petrgazarov/git-repo-name"
  version "0.1.11"
  license "MIT"
  
  resource "shell_script" do
    url "https://github.com/petrgazarov/git-repo-name/releases/download/0.1.11/git-repo-name.sh"
    version "0.1.11"
    sha256 "66a0c43e33f3925856abf11d313ddc69cc4b886642f6b4d7815bba10bafb5e23"
  end

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/petrgazarov/git-repo-name/releases/download/0.1.11/git-repo-name-0.1.11-x86_64-apple-darwin"
      sha256 "bf1a5e42324e4ea75185f9206e429038d82747598a70aa329e4fe72399461416"
    end

    if Hardware::CPU.arm?
      url "https://github.com/petrgazarov/git-repo-name/releases/download/0.1.11/git-repo-name-0.1.11-aarch64-apple-darwin"
      sha256 "ec544354919e3bfa04d2472554d186f180d8942cf7beb3044fa350d4651cfa8e"
    end

    def install
      if Hardware::CPU.intel?
        filename = File.basename("https://github.com/petrgazarov/git-repo-name/releases/download/0.1.11/git-repo-name-0.1.11-x86_64-apple-darwin")
        bin.install filename => "git-repo-name-bin"
      end

      if Hardware::CPU.arm?
        filename = File.basename("https://github.com/petrgazarov/git-repo-name/releases/download/0.1.11/git-repo-name-0.1.11-aarch64-apple-darwin")
        bin.install filename => "git-repo-name-bin"
      end
      
      # Install shell script resource
      resource("shell_script").stage do
        (share/"git-repo-name").install "git-repo-name.sh"
      end
      
      # Install the shell wrapper
      (bin/"git-repo-name").write <<~EOS
        #!/bin/sh
        # This shell script wrapper handles directory changes when using git-repo-name
        exec /bin/sh "#{share}/git-repo-name/git-repo-name.sh" "$@"
      EOS
      
      chmod 0755, bin/"git-repo-name"
    end

    def caveats
      <<~EOS
        Add the following line to your shell profile (such as ~/.bashrc or ~/.zshrc):

          source "$(brew --prefix)/share/git-repo-name/git-repo-name.sh"
      EOS
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/petrgazarov/git-repo-name/releases/download/0.1.11/git-repo-name-0.1.11-aarch64-unknown-linux-gnu"
      sha256 "a0eaeee1cd226284ebec6b36f3739f9ace919bdd94e07cc58edf7edd3c9f1004"
    end

    if Hardware::CPU.intel?
      url "https://github.com/petrgazarov/git-repo-name/releases/download/0.1.11/git-repo-name-0.1.11-x86_64-unknown-linux-gnu"
      sha256 "fd5d24c96859a277d88c161c0d2ead8adba17ad06d8e461c5b4a10bab2dcd2c8"
    end

    def install
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        filename = File.basename("https://github.com/petrgazarov/git-repo-name/releases/download/0.1.11/git-repo-name-0.1.11-aarch64-unknown-linux-gnu")
        bin.install filename => "git-repo-name-bin"
      end

      if Hardware::CPU.intel?
        filename = File.basename("https://github.com/petrgazarov/git-repo-name/releases/download/0.1.11/git-repo-name-0.1.11-x86_64-unknown-linux-gnu")
        bin.install filename => "git-repo-name-bin"
      end
      
      # Install shell script resource
      resource("shell_script").stage do
        (share/"git-repo-name").install "git-repo-name.sh"
      end
      
      # Install the shell wrapper
      (bin/"git-repo-name").write <<~EOS
        #!/bin/sh
        # This shell script wrapper handles directory changes when using git-repo-name
        exec /bin/sh "#{share}/git-repo-name/git-repo-name.sh" "$@"
      EOS
      
      chmod 0755, bin/"git-repo-name"
    end

    def caveats
      <<~EOS
        Add the following line to your shell profile (such as ~/.bashrc or ~/.zshrc):

          source "$(brew --prefix)/share/git-repo-name/git-repo-name.sh"
      EOS
    end
  end

  test do
    system "#{bin}/git-repo-name", "--version"
  end
end 