# frozen_string_literal: true

# This file was generated by https://github.com/petrgazarov/git-repo-name/blob/master/.github/workflows/release_packages.yml
class GitRepoName < Formula
  desc "Sync git repository names between remote and local"
  homepage "https://github.com/petrgazarov/git-repo-name"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/petrgazarov/git-repo-name/releases/download/0.1.1/git-repo-name-0.1.1-x86_64-apple-darwin"
      sha256 "be3acb917b26371a8eaa255ec8a8243ca5c6d38c86b2146883a3e5fafc2f9e2d"
    end

    if Hardware::CPU.arm?
      url "https://github.com/petrgazarov/git-repo-name/releases/download/0.1.1/git-repo-name-0.1.1-aarch64-apple-darwin"
      sha256 "830ec9a6e76db355b414dd949c0df2e24ecb843770f819d30e96393764c9af9e"
    end

    def install
      if Hardware::CPU.intel?
        filename = File.basename("https://github.com/petrgazarov/git-repo-name/releases/download/0.1.1/git-repo-name-0.1.1-x86_64-apple-darwin")
        bin.install filename => "git-repo-name"
      end

      if Hardware::CPU.arm?
        filename = File.basename("https://github.com/petrgazarov/git-repo-name/releases/download/0.1.1/git-repo-name-0.1.1-aarch64-apple-darwin")
        bin.install filename => "git-repo-name"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/petrgazarov/git-repo-name/releases/download/0.1.1/git-repo-name-0.1.1-aarch64-unknown-linux-gnu"
      sha256 "e22b6d2ee5805ed2abb327b4296f4ce85c24412cafd0dda88053804f272fddc5"
    end

    if Hardware::CPU.intel?
      url "https://github.com/petrgazarov/git-repo-name/releases/download/0.1.1/git-repo-name-0.1.1-x86_64-unknown-linux-gnu"
      sha256 "433a40b7d5e90f30d559160e541238bab6fa6c17069005c63758a02d68ef94e2"
    end

    def install
      if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
        filename = File.basename("https://github.com/petrgazarov/git-repo-name/releases/download/0.1.1/git-repo-name-0.1.1-aarch64-unknown-linux-gnu")
        bin.install filename => "git-repo-name"
      end

      if Hardware::CPU.intel?
        filename = File.basename("https://github.com/petrgazarov/git-repo-name/releases/download/0.1.1/git-repo-name-0.1.1-x86_64-unknown-linux-gnu")
        bin.install filename => "git-repo-name"
      end
    end
  end

  test do
    system "#{bin}/git-repo-name", "--version"
  end
end 